### ISSUE TITLE
GoAnything Panel border row

### ISSUE THREAD

**Issue by gpessia** [karelvuong/st-primer#13]
here 1.0.3 - uninstall, clean folder from old files, (re)install but nothing, there are not border on GoAnything Panel, it's a problem of my package?  
![schermata 2015-03-26 alle 08 37 18](https://cloud.githubusercontent.com/assets/68612/6842055/76636af0-d393-11e4-9c5d-681d53635150.png)

**Comment by ghost** [comment]
Hm, not sure what's happening with this, @gpessia. I did a clean install, cleared my cache, and it was working as expected.

**Comment by gpessia** [comment]
@karelvuong I reinstalled everything from scratch, deleting all (cache, package, etc) file from "Applications Support > Sublime Text 3"  but nothing has changed :cry:

**Comment by ghost** [comment]
Just pushed a release for v1.1.0 along with a dark theme. Hopefully this will fix your issue. :smile:

**Comment by gpessia** [comment]
No change :( v1.1.0 - same problem in dark version 

![schermata 2015-03-28 alle 09 30 52](https://cloud.githubusercontent.com/assets/68612/6880359/6ac79e28-d52d-11e4-9f96-00f8627c92c1.png)
![schermata 2015-03-28 alle 09 31 03](https://cloud.githubusercontent.com/assets/68612/6880361/6ac90fe2-d52d-11e4-806c-7624b95a774e.png)
![schermata 2015-03-28 alle 09 31 40](https://cloud.githubusercontent.com/assets/68612/6880360/6ac920ae-d52d-11e4-890a-592e954b0293.png)

**Comment by ghost** [comment]
This has been fixed in v.1.1.2. Thanks @gpessia. :)

**Comment by gpessia** [comment]
> _Nunc est bibendum!_  

PERFECT! :+1:  
![schermata 2015-03-28 alle 20 46 22](https://cloud.githubusercontent.com/assets/68612/6882612/ae4de3a6-d58b-11e4-8167-8cd1b7564d97.png)
