### ISSUE TITLE
The scrollbar needs some adjusting

### ISSUE THREAD

**Issue by gj1118** [karelvuong/st-primer#18]
the scrollbars need some adjusting when the "overlay_scroll_bars": "system" option is set . I cannot see the puck control .

**Comment by ghost** [comment]
Can you submit a screenshot of how this looks like for you, @gj1118?

**Comment by gilbertw1** [comment]
I'm seeing this behavior on osx...here is a screenshot of what mine looks like:

![screen shot on 2015-04-11 at 23-07-58](https://cloud.githubusercontent.com/assets/142303/7104244/f3a95d4e-e09f-11e4-92c8-97e3b4448b4c.png)

As you can see the scroll bar on the side and bottom of the sidebar do not show a puck and are entirely gray. This same behavior is seen in the main editor section as well. Switching "overlay_scroll_bars" to "enabled" fixes the problem. Also, really love the theme!

**Comment by ghost** [comment]
This has been fixed in the next release (v1.1.15). :smile:
