### ISSUE TITLE
Primer Dark window theme isn't working

### ISSUE THREAD

**Issue by omgmog** [karelvuong/st-primer#19]
Hello -- first of all thanks for putting together such a nice theme!

I'm having no problems with the light variation of the theme, but the Dark version doesn't seem to work at all.

![](http://i.imgur.com/FBz2yUJ.png)

I installed the package using Wbond's Package Manager, and I've confirmed that the "Primer Dark.sublime-theme" file exists, but it just doesn't want to apply.

I'm using `Sublime Text 2, build 2221` on Linux.

Any thoughts?

**Comment by ghost** [comment]
Hey @omgmog, removing the first `"theme": "Primer.sublime-theme"` on L3 should fix it. :smile:

**Comment by omgmog** [comment]
Sorry but it doesn't -- the value is being over-ridden, so that being there and then being set on the following line is fine:

![](http://i.imgur.com/EJYopKS.png)

**Comment by omgmog** [comment]
Okay I've fixed it here.

The problem was caused by the JSON for that theme being malformed. You've got some trailing commas in blocks (due to commenting bits out) that shouldn't be there.

I'll make a pull request to fix if you like

**Comment by karelvuong** [comment]
Can you take a screenshot of your console (via <kbd>CTRL</kbd> + <kbd>`</kbd>)?

**Comment by ghost** [comment]
Sure, that'd be helpful, @omgmog!

**Comment by omgmog** [comment]
![](http://i.imgur.com/3x8bCLS.png) :+1:
