### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by ghost** [karelvuong/st-primer#2]
The current screenshots only reveal accent colors taking effect on the active tab and icons in the bottom panel.

![image](https://cloud.githubusercontent.com/assets/2213571/6819683/438a835a-d282-11e4-8d4e-c7fe8f7afd9f.png)

**Comment by ghost** [comment]
Also need to update screenshots to show new input field styles.

**Comment by ghost** [comment]
Add screenshots for dark theme with accompanying accent colors.

**Comment by thecodechef** [comment]
Here are the screenshots for the Primer Dark Theme

![screenshot from 2015-04-17 17 08 20](https://cloud.githubusercontent.com/assets/5333019/7211829/dbbb3c64-e524-11e4-8862-03fb30d4ea04.png)
![screenshot from 2015-04-17 17 03 50](https://cloud.githubusercontent.com/assets/5333019/7211882/592ef640-e525-11e4-9d54-82029115420b.png)
![screenshot from 2015-04-17 17 06 01](https://cloud.githubusercontent.com/assets/5333019/7211850/ff265314-e524-11e4-8208-81a3b0894e5c.png)
![screenshot from 2015-04-17 17 06 33](https://cloud.githubusercontent.com/assets/5333019/7211854/04ca561c-e525-11e4-913d-d3492d384a6d.png)
![screenshot from 2015-04-17 17 07 09](https://cloud.githubusercontent.com/assets/5333019/7211861/19a75ec2-e525-11e4-86e7-8e2d1c7276ae.png)
![screenshot from 2015-04-17 17 07 52](https://cloud.githubusercontent.com/assets/5333019/7211863/1df594bc-e525-11e4-8b7d-9de336d8b2c4.png)
