### ISSUE TITLE
Add Scrollbars to Theme

### ISSUE THREAD

**Issue by thecodechef** [karelvuong/st-primer#21]
plz scrollbars to the theme i had switch back to my other fav theme cause of its scrollbars  btw its Theme - Numix

**Comment by ghost** [comment]
Are scrollbars not appearing for you? What platform and version of Sublime Text are you using?

**Comment by thecodechef** [comment]
I'm on Ubuntu 14.04 & ST 3083

**Comment by ghost** [comment]
Are the scrollbars hidden for you?

**Comment by thecodechef** [comment]
no

**Comment by ghost** [comment]
Can you post a screenshot of them?

**Comment by thecodechef** [comment]
![image](https://cloud.githubusercontent.com/assets/5333019/7142761/82d621f8-e2a0-11e4-8eb7-62bb3e34af83.png)

**Comment by ghost** [comment]
Do the scrollbars appear when you're scrolling in the sidebar?

**Comment by thecodechef** [comment]
nope

**Comment by ghost** [comment]
And you've installed the theme via Package Control? 

I won't be able to look into this as I'm on OS X and the scrollbars are working for me. You can try changing setting `{ "overlay_scroll_bars": "enabled" }` in your `Settings - User` to see if that will fix it. 

If you want, feel free to play around with it and see if you can fix it. :smile:

**Comment by thecodechef** [comment]
ok i'll try that lets see if it brb

**Comment by thecodechef** [comment]
nope that didnt work

**Comment by thecodechef** [comment]
well i even turn my settings in unity tweak tool back overlay and that still didn't work

**Comment by thecodechef** [comment]
btw you do linux is free right you can run it virualbox or another vm software on mac and test this out

**Comment by thecodechef** [comment]
go to ubuntu.com and download it

**Comment by thecodechef** [comment]
hey i found out what the problem was the scrollbars were so dark they actually blended in with the scrollbar bg so would it be poosible to add color variations to the scrollbar like theme_primer_scrollbars_blue or somthing to that effect cause i think that would look really cool. tell me what ya think about it

**Comment by thecodechef** [comment]
Here is an Example of the scrollbars 
![image](https://cloud.githubusercontent.com/assets/5333019/7143318/5c9f36e2-e2a4-11e4-8c7d-3d79ee03592d.png)

**Comment by ghost** [comment]
It's a bit too blinding in my opinion. Though, you're happy to customize the theme as you like - it is open source after all. :smile:

**Comment by ghost** [comment]
The issue has been fixed in release v1.1.5.
