### ISSUE TITLE
Fix Code Completion for Dark Theme plz!!

### ISSUE THREAD

**Issue by thecodechef** [karelvuong/st-primer#22]
Hey Thanks for fixing the scrollbars  anyway just noticed that the code completion for the dark theme is all white and doesnt match the theme at all so i went in and changed some stuff and i got this effect

![screenshot from 2015-04-15 23 52 08](https://cloud.githubusercontent.com/assets/5333019/7174337/dfae76ba-e3cb-11e4-8e1b-40291dfeca5c.png)

here are the settings i changed

![screenshot from 2015-04-15 23 50 05](https://cloud.githubusercontent.com/assets/5333019/7174343/f944133c-e3cb-11e4-9b87-f75df168eaf2.png)

![screenshot from 2015-04-15 23 48 05](https://cloud.githubusercontent.com/assets/5333019/7174350/031495b2-e3cc-11e4-9d6d-e02af505891a.png)

![screenshot from 2015-04-15 23 49 36](https://cloud.githubusercontent.com/assets/5333019/7174353/07375530-e3cc-11e4-9451-27e87e375eb5.png)

if you could implement these with your own changes it would be great Thanks

**Comment by ghost** [comment]
Hey, thanks for this, @thecodechef. This will be included in v1.1.6. :smile:

**Comment by thecodechef** [comment]
No Problem Happy to Help
