### ISSUE TITLE
Can't distinguish selected menu item in light mode

### ISSUE THREAD

**Issue by maxim** [karelvuong/st-primer#25]
In light mode it's very hard to tell which list item is selected. The difference is very subtle, especially if selected item is down the list.

![hard-to-tell-selected](https://cloud.githubusercontent.com/assets/7758/7306771/c4540000-e9d5-11e4-8188-6df818187403.png)

**Comment by urosevic** [comment]
Agree. And same is for sidebar.
Maybe is better to have selected item blue background as for Tab.
![primer-light-sidebar-selected](https://cloud.githubusercontent.com/assets/6445007/7336782/5bdbf0ba-ec0e-11e4-97ae-b8df5ab2afbc.png)

**Comment by maxim** [comment]
P.S. I love this theme. So far the most tasteful makeover I've seen done for ST (subjective obviously).
