### ISSUE TITLE
How to enable icon_file_type at SideBar Panel

### ISSUE THREAD

**Issue by HeroSony** [karelvuong/st-primer#29]
Hello! how can i enable the icon file type at the left sidebar panel in Primer theme by Sublime Text 3?

![s](https://cloud.githubusercontent.com/assets/4160246/7862914/46d4297e-0583-11e5-9a5e-b79ec36e78e0.png)

**Comment by ghost** [comment]
Hey @HeroSony, what do you mean? The icons are there in the screenshot ^.

**Comment by HeroSony** [comment]
I want to enable these icon in Primer theme but I cannot.

![1](https://cloud.githubusercontent.com/assets/4160246/7975785/4fcc77fc-0a9c-11e5-83fe-efd25a6b606b.png)

Could you help me, Please?

**Comment by ghost** [comment]
Are you on Sublime Text 2? File type icons are supported in Sublime Text 3.

**Comment by HeroSony** [comment]
Ok, Maybe I need to update Sublime Text 3, anyway thank for your help :)
