### ISSUE TITLE
Icon for file type python is not very clear

### ISSUE THREAD

**Issue by reorx** [karelvuong/st-primer#30]
The icon st-primer used for python file:

https://github.com/karelvuong/st-primer/blob/master/icons%2Ffile_type_python%402x.png

looks a little bit dim compare to the one that cobalt2 used:

https://github.com/wesbos/cobalt2/blob/master/icons%2Ffile_type_python%402x.png

I replaced it with cobalt2's, comparison as below:

Original Primer:
![screen shot 2015-05-29 at 13 12 53](https://cloud.githubusercontent.com/assets/405972/7876937/08b77726-0606-11e5-970e-f5dddf0f498c.png)

With python icon replaced with cobalt2's:
![screen shot 2015-05-29 at 13 18 48](https://cloud.githubusercontent.com/assets/405972/7876940/0e4a215c-0606-11e5-8cef-19b17ede3e13.png)

In my opinion the latter is better, how do you think :)

**Comment by ghost** [comment]
Love it @reorx! Thanks for this, I'll add it in the next release.

**Comment by ghost** [comment]
This has been committed and is staged for the next release. Closing this issue!

**Comment by reorx** [comment]
Nice job :)
