### ISSUE TITLE
Find in Files panel is partially cut off

### ISSUE THREAD

**Issue by TrevorBurnham** [karelvuong/st-primer#33]
I've installed Primer in Sublime Text build 3083 running on OS X 10.10.3. The Find panel looks great:

![image](https://cloud.githubusercontent.com/assets/224895/8211769/5dfcf47e-14e6-11e5-9ad4-99b0427a7ee6.png)

But in the Find in Files panel, the Replace row is partially cut off:

![image](https://cloud.githubusercontent.com/assets/224895/8211804/7d6f3d1c-14e6-11e5-957c-9be01c8e5be6.png)

(It's cut off whether the status bar is shown or not.)

**Comment by ghost** [comment]
Are you able to resize the Find in Files panel? You should be able to drag and resize it up if you position your cursor near the top edge.

**Comment by TrevorBurnham** [comment]
Aha! Dragging up did indeed fix the issue, and dragging down won't let me reduce the height back below a sensible level. Thanks!
