### ISSUE TITLE
"Find in files" is cut at the bottom

### ISSUE THREAD

**Issue by gianaguilar** [karelvuong/st-primer#38]
<img width="1147" alt="screen shot 2015-07-14 at 1 42 02 pm" src="https://cloud.githubusercontent.com/assets/1571560/8667158/245e57a0-2a2e-11e5-81a7-ccd74129904e.png">

**Comment by SalGnt** [comment]
As said in #33, simply grab the bar and pull-up to fix it.

**Comment by ghost** [comment]
^ Yup, that's the fix. Thanks @SalGnt!
