### ISSUE TITLE
It was really hard to see which one I choosed

### ISSUE THREAD

**Issue by ilovezy** [karelvuong/st-primer#42]
here is a little problem for the primer -light theme
![qq 20150731123427](https://cloud.githubusercontent.com/assets/8774988/9000844/b298189e-3780-11e5-949c-dc67b739c241.png)
the selected item's background color is too similar to white, It's really hard for me to see which one did I  
choosed,  can you add a setting to set the background color a litte more obviously

**Comment by maqboolkhan** [comment]
+1
