### ISSUE TITLE
Go Anything... Background color 

### ISSUE THREAD

**Issue by gpessia** [karelvuong/st-primer#6]
It is not the same as other panels.
![schermata 2015-03-25 alle 08 10 42](https://cloud.githubusercontent.com/assets/68612/6819766/c44a17d2-d2c6-11e4-800d-dfb6cd87ec50.png)

**Comment by ghost** [comment]
Thanks for reporting this, @gpessia. 

This has been fixed and is currently staged for the next release (v1.0.1). :smiley:

**Comment by ghost** [comment]
[Release v1.0.1](https://github.com/karelvuong/st-primer/releases/tag/1.0.1) has been published!
