### ISSUE TITLE
Not working with ST2

### ISSUE THREAD

**Issue by flodolo** [karelvuong/st-primer#7]
Package is reported as compatible with ST2, but when I try to enable it (OS X, not sure it matters) I get a completely unusable window.

![schermata 2015-03-25 alle 11 10 28](https://cloud.githubusercontent.com/assets/3644868/6822386/95f45f14-d2df-11e4-8f65-f273a58fd4ef.png)

**Comment by ghost** [comment]
Thanks for reporting this, @flodolo. I'll take a look into this later.

**Comment by ghost** [comment]
Turns out I had a bunch of trailing commas, this has been fixed and is staged for the next release v1.0.3. :smiley:

**Comment by ghost** [comment]
Pushed for release! Expect this update soon, @flodolo.

**Comment by flodolo** [comment]
Great, thanks :+1:
